export const LOAD_INITIAL_STATE = "LOAD_INITIAL_STATE";
export const API_REQUEST_FAILURE = "API_REQUEST_FAILURE";
export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";

export const SELECT_ACTIVITY_REQUEST = "SELECT_ACTIVITY_REQUEST";
export const SWITCH_TO_VIEW = "SWITCH_TO_HEART_VIEW";

export const TURN_PAGE_REQUEST = "TURN_PAGE_REQUEST";

export const CREATE_WORLD_REQUEST = "CREATE_WORLD_REQUEST";
export const DESTROY_WORLD_REQUEST = "DESTROY_WORLD_REQUEST";

export const SELECT_CHAMBER = "SELECT_CHAMBER"
